name: Linux C++ CI

on:
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prerequisites
      run: |
          sudo apt-get update
          sudo apt-get install -y ncbi-blast+
    - name: make
      run: make
    - name: test
      run: ./test_stxtyper.sh
    - name: Upload artifacts on failure
      uses: actions/upload-artifact@v4
      if: ${{ failure() }} # only run if the job fails
      with: 
        name: stxtyper-failed-test-linux
        path: |
            ./*
            test/* 
        retention-days: 14

  build-docker:
      
      runs-on: ubuntu-latest
  
      steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build to test
        uses: docker/build-push-action@v5
        with:
          push: false

