name: Linux C++ CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prerequisites
      run: |
          sudo apt-get update
          sudo apt-get install -y ncbi-blast+
    - name: make
      run: make
    - name: test
      run: ./test_stxtyper.sh
    - name: Upload artifacts on failure
      uses: actions/upload-artifact@v4
      if: ${{ failure() }} # only run if the job fails
      with: 
        name: build-and-test-artifact
        path: |
            ./*
            test/* 
        retention-days: 14
